import * as React from 'react';
import Header from '../component/Header';
import Head from 'next/head';
export interface INewWordProps {
}

export default function NewWord (props: INewWordProps) {
  return (
    <div>
      <Head>
        <title>WordMemo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.pinimg.com/736x/d1/2c/0c/d12c0c317c3ae48c9fb11127af539d00.jpg" />
      </Head>
      <Header active={'add-word'}/>
    </div>
  );
}
