import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../component/Header'
import Question from '../component/learn/question'
const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>WordMemo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.pinimg.com/736x/d1/2c/0c/d12c0c317c3ae48c9fb11127af539d00.jpg" />
      </Head>
      <Header active={'home'}/>
      <Question/>
    </div>
  )
}

export default Home
