import * as React from 'react';
import Head from 'next/head';
import Header from '../component/Header';
import WordList, { IWordItem } from '../component/wordlist/WordList';
import { useEffect } from 'react';
import { API } from '../config/api';
import axios from 'axios';
import { useState } from 'react';
export interface IWordListPageProps  {
  
}

export default function WordListPage (props: IWordListPageProps) {

  const [wordList, setWordList] = useState<IWordItem[]>([]);

  useEffect(() => {
    axios.get(API.route+"api/test")
    .then(data => {
      console.log("data.data.words", data.data.words);
      const words = (data.data.words as IWordItem[]);
      const newWords = words.map(val => {
        return {
          word: val.word,
          meaning: val.meaning,
          pronun: val.pronun,
          sentence: val.sentence,
        }
      })
      setWordList(newWords);
    })
    .catch(error => {
      console.log(error);
    }) 
  },[])

  return (
    <div>
      <Head>
        <title>WordMemo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./icon.png" />
      </Head>
      <Header active={'word-list'}/>
      <WordList wordList={wordList}/>
      

    </div>
  );
}
